mfp:
  implementation: ${MFP_IMPLEMENTATION:library}
  py-mfp:
    path: ${MFP_PYTHON_PATH}

python:
  binary: ${MFP_PYTHON:python3}

browsercookies:
  cookie-loader-path: ${MFP_PYTHON_COOKIE_LOADER_PATH:}
  cookies-db-path: ${MFP_PYTHON_COOKIE_DB_PATH}