openapi: 3.0.3
info:
  title: Diary Food API
  version: 1.0.0
tags:
  - name: food
    description: Diary food information
  - name: meals
    description: Meals information
  - name: sessionCookies
    description: Session cookies
paths:
  /v1/food:
    get:
      tags:
        - food
      summary: Get Diary Food
      operationId: getFoodDiary
      parameters:
        - name: date
          in: query
          required: true
          description: Date for retrieving diary food
          schema:
            type: string
            format: date
        - name: toDate
          in: query
          description: End date for retrieving diary food (optional)
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FoodDaysResponse'

  /v1/meals:
    get:
      tags:
        - meals
      summary: Get Meals
      operationId: getMeals
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableMealsResponse'

  /v1/session:
    post:
      tags:
        - sessionCookies
      summary: Update session cookies
      operationId: updateSessionCookies
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Successful response

components:
  schemas:
    FoodDTO:
      type: object
      properties:
        name:
          type: string
        brand:
          type: string
        amount:
          type: number
          format: double
        unit:
          type: string
      required:
        - name
        - amount

    DayMealDTO:
      type: object
      properties:
        name:
          type: string
        food:
          type: array
          items:
            $ref: '#/components/schemas/FoodDTO'
      required:
        - name
        - food

    FoodDayDTO:
      type: object
      properties:
        date:
          type: string
          format: date
        meals:
          type: array
          items:
            $ref: '#/components/schemas/DayMealDTO'
      required:
        - date
        - meals

    FoodDaysResponse:
      type: object
      properties:
        days:
          type: array
          items:
            $ref: '#/components/schemas/FoodDayDTO'
      required:
        - days

    MealInfoDTO:
      type: object
      properties:
        name:
          type: string
      required:
        - name

    AvailableMealsResponse:
      type: object
      properties:
        meals:
          type: array
          items:
            $ref: '#/components/schemas/MealInfoDTO'
      required:
        - meals