name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        GITHUBPACKAGESUSERNAME: ${{ secrets.GITHUBPACKAGESUSERNAME }}
        GITHUBPACKAGESPASSWORD: ${{ secrets.GITHUBPACKAGESPASSWORD }}
      with:
        name: marcosav/myfitnesspal-api-server
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: GITHUBPACKAGESUSERNAME,GITHUBPACKAGESPASSWORD
        platforms: linux/amd64,linux/arm64/v8
